// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6IQfzr8E9ZzDp97vbOhYp40zNgiOFxc',
    appId: '1:788459588015:web:b99c10fae9860e72e5075a',
    messagingSenderId: '788459588015',
    projectId: 'messenger-bb0ba',
    authDomain: 'messenger-bb0ba.firebaseapp.com',
    storageBucket: 'messenger-bb0ba.appspot.com',
    measurementId: 'G-46NZN6Z938',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1-ffapp4b-ddzqr9zehes13wQGXNHxg',
    appId: '1:788459588015:android:82917f6acd08010ce5075a',
    messagingSenderId: '788459588015',
    projectId: 'messenger-bb0ba',
    storageBucket: 'messenger-bb0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkPDYQrFAyMuxF_G_MnlMFcHqIFgKXik',
    appId: '1:788459588015:ios:b5abd601711e1cc4e5075a',
    messagingSenderId: '788459588015',
    projectId: 'messenger-bb0ba',
    storageBucket: 'messenger-bb0ba.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkPDYQrFAyMuxF_G_MnlMFcHqIFgKXik',
    appId: '1:788459588015:ios:d7ad5748f543015be5075a',
    messagingSenderId: '788459588015',
    projectId: 'messenger-bb0ba',
    storageBucket: 'messenger-bb0ba.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
